<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@unitedplasticscorp.com',
		'to' => 'info@unitedplasticscorp.com'
	),
	'fields' => array(
		'custom_U4242' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Your Full Name *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Your Full Name *\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email Address *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email Address *\' is required.',
				'format' => 'Field \'Email Address *\' has an invalid email.'
			)
		),
		'custom_U4251' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Please provide a description of your request *
Write as much detail as possible. The more we know, the better we can help you',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Please provide a description of your request *
Write as much detail as possible. The more we know, the better we can help you\' is required.'
			)
		),
		'custom_U4247' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Contact Number *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Number *\' is required.'
			)
		),
		'custom_U4259' => array(
			'order' => 1,
			'type' => 'checkboxgroup',
			'label' => 'Please direct my request to the following department:
Optional. Leave unselected if you\'re not sure',
			'required' => false,
			'optionItems' => array(
				'Architectural',
				'Industrial'
			),
			'errors' => array(
				'format' => 'Field \'Please direct my request to the following department:
Optional. Leave unselected if you\'re not sure\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
